spring:
  application:
    name: contactApi
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}   # Use the environment variable for sensitive data
      chat:
        options:
          model: gpt-4o           # Specify the AI model
  weather:
    api-key: ${WEATHER_API_KEY}  # Use the environment variable for sensitive data
    api-url: http://api.weatherapi.com/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/testdatabase
    username: postgresuser
    password: securepassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
      format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
